// bone-business/tpa-sass-react/src/components/RenderEngine/base/Form/index.tsx

import React, { useCallback, useMemo, useEffect, useRef } from "react";
import { Form as AntForm } from "antd";
import { useScopeData } from "../../hooks/useScopeData";
import { isEmpty } from "lodash-es";
import { FormProps, defaultFormProps } from "./props";
import PKInput from "../Input";
import PKSelectDrop from "../SelectDrop";
import PKBlock from "../Block";
import PKMainBlock from "../MainBlock";

const componentRegistry = {
  PKInput,
  PKSelectDrop,
  PKBlock,
  PKMainBlock,
};

const PKForm: React.FC<FormProps> = (props) => {
  const mergedProps = { ...defaultFormProps, ...props };
  const [form] = AntForm.useForm();
  const scopeData = useScopeData();

  const validateManager = scopeData.getData("validateManager");
  const rulesManager = scopeData.getData("rulesManager");

  const submitRuleList = useMemo(() => rulesManager?.get(2, "Form") || [], [rulesManager]);

  const validateFields = useCallback(async () => {
    try {
      await form.validateFields();
      return { success: true };
    } catch (error: any) {
      const messages = error.errorFields?.map((item: any) => item.errors[0]) || [];
      return { success: false, messages };
    }
  }, [form]);

  const validate = useCallback(async () => {
    const formValidResult = await validateFields();

    if (isEmpty(submitRuleList)) {
      return formValidResult;
    }

    return {
      success: formValidResult.success,
      messages: formValidResult.messages || [],
    };
  }, [validateFields, submitRuleList]);

  useEffect(() => {
    validateManager?.push?.(validate);
  }, [validateManager, validate]);

  const renderComponent = useCallback((schemaNode: any): React.ReactNode => {
    if (!schemaNode) return null;

    const Component = componentRegistry[schemaNode.type as keyof typeof componentRegistry];
    
    if (!Component) {
      console.warn(`组件 ${schemaNode.type} 未找到`);
      return null;
    }

    return <Component key={schemaNode.id} {...schemaNode} />;
  }, []);

  const stickyItems = mergedProps.body?.slice(0, 2);
  const regularItems = mergedProps.body?.slice(2);

  return (
    <div className={`w-full bg-gray-50 ${mergedProps.body?.length > 0 ? "pt-1" : ""}`}>
      <AntForm form={form} labelPosition="top">
        <div className="bg-white mb-2 mx-2 rounded-lg">
          {mergedProps.isAffix && (
            <div className="sticky top-0 z-50 bg-white shadow-lg">
              {stickyItems?.map((item: any) => (
                <div key={item.id} className="border-b border-gray-200">
                  {renderComponent(item)}
                </div>
              ))}
            </div>
          )}
          
          {!mergedProps.isAffix && stickyItems?.map((item: any) => (
            <div key={item.id} className="border-b border-gray-200">
              {renderComponent(item)}
            </div>
          ))}

          {regularItems?.map((item: any, index: number) => (
            <div 
              key={item.id} 
              className={index < regularItems.length - 1 ? "border-b border-gray-200" : ""}
            >
              {renderComponent(item)}
            </div>
          ))}
        </div>

        <div className="sticky bottom-0 z-10">
          <div className="flex justify-center w-full bg-white border-t border-gray-200 py-3">
            {/* PKButtonGroup 组件将在后续添加 */}
          </div>
        </div>
      </AntForm>
    </div>
  );
};

export default PKForm;

// bone-business/tpa-sass-vue3/src/components/RenderEngine/base/Form/index.vue
<script setup>
import { EventOwnerEnum } from "@/enums/event/EventOwnerEnum";
import { createProps } from "./form";
import { useScopeData } from "../../hooks/useScopeData";
import { useSubmitRule } from "../../hooks/useSubmitRule";
import { isEmpty } from "lodash-es";

defineOptions({
  name: "Form",
});

const scopeData = useScopeData();
const dataManager = scopeData.getData("dataManager");
const validateManager = scopeData.getData("validateManager");
const componentManager = scopeData.getData("componentManager");
const rulesManager = scopeData.getData("rulesManager");
const data = scopeData.getData("data");

const props = defineProps(createProps());

const submitRuleList = computed(() => rulesManager.get(2, "Form"));

/** 校验表单静态规则 */
const formRef = ref(null);
const validateFields = async () => {
  if (!formRef.value) return { success: true };
  try {
    await formRef.value.validate();
    return { success: true };
  } catch (error) {
    const values = Object.values(error).flat();
    const messages = values.map((item) => item.message);
    return { success: false, messages };
  }
};

/** 校验表单静态规则以及提交规则 */
const validate = () => {
  return new Promise(async (resolve) => {
    const formValidResult = await validateFields();

    if (isEmpty(submitRuleList.value)) {
      resolve(formValidResult);
      return;
    }

    const submitValidResult = useSubmitRule(
      submitRuleList.value,
      dataManager,
      componentManager
    );
    resolve({
      success: formValidResult.success && submitValidResult.success,
      messages: isEmpty(formValidResult.messages)
        ? submitValidResult.messages
        : [...formValidResult.messages, ...submitValidResult.messages],
    });
  });
};

validateManager.push(validate);
</script>

<template>
  <div
    class="w-full bg-[var(--el-bg-color-page)]"
    :class="{ 'pt-1': body.length > 0 }"
  >
    <el-form ref="formRef" :model="data" label-position="top">
      <div class="bg-[var(--el-bg-color)] mb-2 mx-2 rounded-lg">
        <div
          :class="
            isAffix ? 'sticky top-0 z-99 bg-[var(--el-bg-color)] shadow-lg' : ''
          "
        >
          <div
            class="border-b border-[var(--el-border-color-light)]"
            v-for="item in body?.slice(0, 2)"
            :key="item.id"
          >
            <component :is="item.type" v-bind="item" />
          </div>
        </div>
        <div
          class="not-last:border-b border-[var(--el-border-color-light)]"
          v-for="item in body?.slice(2)"
          :key="item.id"
        >
          <component :is="item.type" v-bind="item" />
        </div>
      </div>

      <div class="sticky bottom-0 z-10">
        <div
          class="flex-x-center w-full bg-[var(--el-bg-color)] border-t border-[var(--el-border-color-lighter)] py-3"
        >
          <PKButtonGroup
            :buttonList="eventTriggerList"
            :ownerId="id"
            :owner="EventOwnerEnum.Form"
          />
        </div>
      </div>
    </el-form>
  </div>
</template>

<style lang="scss" scoped></style>
