// bone-business/tpa-sass-react/src/components/Claim/ApplyInfoDialog/index.tsx
import React, { useEffect, useState } from "react";
import { Modal, Form, Input } from "antd";
import ClaimAPI, { IApplyInfo } from "@/api/claim";

interface ApplyInfoDialogProps {
  visible: boolean;
  onClose: () => void;
  claimId: string;
}

const ApplyInfoDialog: React.FC<ApplyInfoDialogProps> = ({ visible, onClose, claimId }) => {
  const [applyInfo, setApplyInfo] = useState<IApplyInfo>({
    applyName: "",
    applyIdentityNo: "",
    applyType: "",
    applyTime: "",
    applyPhone: "",
    outInsureName: "",
    outInsureIdentityNo: "",
    outInsureTime: "",
    policyNo: "",
    collectName: "",
    accountNo: "",
    bankName: "",
    bankAddress: "",
  });

  const getApplyInfo = async () => {
    if (claimId) {
      const res = await ClaimAPI.applyInfo(claimId);
      setApplyInfo(res);
    }
  };

  useEffect(() => {
    if (visible && claimId) {
      getApplyInfo();
    }
  }, [visible, claimId]);

  return (
    <Modal
      title="查看报案信息"
      open={visible}
      onCancel={onClose}
      footer={[
        <button key="cancel" onClick={onClose}>
          取消
        </button>
      ]}
      width="30%"
      maskClosable={false}
    >
      <div style={{ maxHeight: "500px", overflowY: "auto", padding: "8px" }}>
        <Form layout="horizontal" labelAlign="left">
          <p>申请信息</p>
          <Form.Item label="申请人姓名">
            <Input value={applyInfo.applyName} disabled />
          </Form.Item>
          <Form.Item label="申请人身份证">
            <Input value={applyInfo.applyIdentityNo} disabled />
          </Form.Item>
          <Form.Item label="申请类型">
            <Input value={applyInfo.applyType} disabled />
          </Form.Item>
          <Form.Item label="申请时间">
            <Input value={applyInfo.applyTime} disabled />
          </Form.Item>
          <Form.Item label="联系方式">
            <Input value={applyInfo.applyPhone} disabled />
          </Form.Item>
          <p>报案信息</p>
          <Form.Item label="出险人姓名">
            <Input value={applyInfo.outInsureName} disabled />
          </Form.Item>
          <Form.Item label="出险人证件号">
            <Input value={applyInfo.outInsureIdentityNo} disabled />
          </Form.Item>
          <Form.Item label="出险时间">
            <Input value={applyInfo.outInsureTime} disabled />
          </Form.Item>
          <Form.Item label="保单号">
            <Input value={applyInfo.policyNo} disabled />
          </Form.Item>
          <Form.Item label="领款人姓名">
            <Input value={applyInfo.collectName} disabled />
          </Form.Item>
          <Form.Item label="银行卡号">
            <Input value={applyInfo.accountNo} disabled />
          </Form.Item>
          <Form.Item label="开户行">
            <Input value={applyInfo.bankName} disabled />
          </Form.Item>
          <Form.Item label="开户行地址">
            <Input value={applyInfo.bankAddress} disabled />
          </Form.Item>
        </Form>
      </div>
    </Modal>
  );
};

export default ApplyInfoDialog;

// bone-business/tpa-sass-vue3/src/components/Claim/ApplyInfoDialog.vue
<script setup lang="ts">
import ClaimAPI, { IApplyInfo } from "@/api/claim";
defineOptions({
  name: "HangupDialog",
});

const emit = defineEmits(["close"]);
const dialogVisible = defineModel({ type: Boolean, default: false });
const props = defineProps({
  claimId: {
    type: String,
    default: "",
  },
});

const applyInfo = ref<IApplyInfo>({
  applyName: "",
  applyIdentityNo: "",
  applyType: "",
  applyTime: "",
  applyPhone: "",
  outInsureName: "",
  outInsureIdentityNo: "",
  outInsureTime: "",
  policyNo: "",
  collectName: "",
  accountNo: "",
  bankName: "",
  bankAddress: "",
});

const getApplyInfo = async () => {
  const res = await ClaimAPI.applyInfo(props.claimId);
  applyInfo.value = res;
};

const onClose = () => {
  dialogVisible.value = false;
  emit("close");
};

onMounted(() => {
  getApplyInfo();
});
</script>

<template>
  <el-dialog
    v-model="dialogVisible"
    :before-close="onClose"
    title="查看报案信息"
    width="30%"
    :close-on-click-modal="false"
  >
    <div class="p-2 max-h-[500px] overflow-y-auto">
      <el-form label-width="auto" label-position="left">
        <p>申请信息</p>
        <el-form-item label="申请人姓名">
          <el-input v-model="applyInfo.applyName" disabled />
        </el-form-item>
        <el-form-item label="申请人身份证">
          <el-input v-model="applyInfo.applyIdentityNo" disabled />
        </el-form-item>
        <el-form-item label="申请类型">
          <el-input v-model="applyInfo.applyType" disabled />
        </el-form-item>
        <el-form-item label="申请时间">
          <el-input v-model="applyInfo.applyTime" disabled />
        </el-form-item>
        <el-form-item label="联系方式">
          <el-input v-model="applyInfo.applyPhone" disabled />
        </el-form-item>
        <p>报案信息</p>
        <el-form-item label="出险人姓名">
          <el-input v-model="applyInfo.outInsureName" disabled />
        </el-form-item>
        <el-form-item label="出险人证件号">
          <el-input v-model="applyInfo.outInsureIdentityNo" disabled />
        </el-form-item>
        <el-form-item label="出险时间">
          <el-input v-model="applyInfo.outInsureTime" disabled />
        </el-form-item>
        <el-form-item label="保单号">
          <el-input v-model="applyInfo.policyNo" disabled />
        </el-form-item>
        <el-form-item label="领款人姓名">
          <el-input v-model="applyInfo.collectName" disabled />
        </el-form-item>
        <el-form-item label="银行卡号">
          <el-input v-model="applyInfo.accountNo" disabled />
        </el-form-item>
        <el-form-item label="开户行">
          <el-input v-model="applyInfo.bankName" disabled />
        </el-form-item>
        <el-form-item label="开户行地址">
          <el-input v-model="applyInfo.bankAddress" disabled />
        </el-form-item>
      </el-form>
    </div>

    <template #footer>
      <div class="flex justify-center">
        <el-button @click="onClose">取消</el-button>
      </div>
    </template>
  </el-dialog>
</template>

<style lang="scss" scoped></style>
