// bone-business/tpa-sass-react/src/components/RenderEngine/base/SmartInput/index.tsx
import React, { useState, useEffect } from 'react';
import { Input, InputNumber, DatePicker, Select } from 'antd';
import dayjs from 'dayjs';

// Components
import SelectDropWithoutForm from '../SelectDropWithoutForm';
import SelectCtrlWithoutForm from '../SelectCtrlWithoutForm';

// Enums
import { BaseCompType } from '@/enums/baseComp/BaseCompEnum';
import { DataFormatEnum } from '@/enums/baseComp/DataFormatEnum';
import { SelectTypeEnum } from '@/enums/baseComp/SelectTypeEnum';
import { FilterTypeEnum } from '@/enums/baseComp/FilterTypeEnum';
import { getDateFormat, getDateRangeType, getDateTimeType } from '@/enums/baseComp/DateFormatEnum';

const { RangePicker } = DatePicker;

interface SmartInputProps {
  type: string;
  modelValue: any;
  onChange: (value: any) => void;
  limitedLength?: number;
  decimalDigit?: number;
  min?: number;
  max?: number;
  multiples?: number;
  dateFormatType?: number;
  selectDatasource?: any[];
  selectLevel?: number;
  selectType?: SelectTypeEnum;
  filterType?: FilterTypeEnum;
  earliestDatetimeType?: number;
  earliestDatetime?: string;
  latestDatetimeType?: number;
  latestDatetime?: string;
  dataFormat?: DataFormatEnum;
}

const SmartInput: React.FC<SmartInputProps> = ({
  type,
  modelValue,
  onChange,
  limitedLength,
  decimalDigit,
  min,
  max,
  multiples,
  dateFormatType,
  selectDatasource,
  selectLevel,
  selectType,
  filterType,
  earliestDatetimeType,
  earliestDatetime,
  latestDatetimeType,
  latestDatetime,
  dataFormat
}) => {
  const [internalValue, setInternalValue] = useState(modelValue);

  useEffect(() => {
    setInternalValue(modelValue);
  }, [modelValue]);

  const handleChange = (value: any) => {
    setInternalValue(value);
    onChange(value);
  };

  const normalizedType = type.replace('PK', '');

  const isValidNumber = (value: any) => {
    return value !== null && value !== undefined && !isNaN(Number(value));
  };

  const targetDecimalDigit = isValidNumber(decimalDigit) && decimalDigit >= 0 ? decimalDigit : 0;
  const targetMin = isValidNumber(min) ? Number(min) : null;
  const targetMax = isValidNumber(max) ? Number(max) : null;
  const targetMultiples = isValidNumber(multiples) && multiples > 0 ? Number(multiples) : null;
  const dateFormat = getDateFormat(dateFormatType);
  const dateTimeType = getDateTimeType(dateFormatType);
  const dateRangeType = getDateRangeType(dateFormatType);
  const isMultiple = selectType === SelectTypeEnum.multiple;
  const isFilter = filterType === FilterTypeEnum.Supported;

  const disabledDate = (date: dayjs.Dayjs) => {
    let earliestDate = null;
    if (earliestDatetimeType === 0 && earliestDatetime) {
      earliestDate = dayjs(earliestDatetime).toDate();
    } else if (earliestDatetimeType === 1) {
      earliestDate = dayjs().startOf('day').toDate();
    }

    let latestDate = null;
    if (latestDatetimeType === 0 && latestDatetime) {
      latestDate = dayjs(latestDatetime).toDate();
    } else if (latestDatetimeType === 1) {
      latestDate = dayjs().endOf('day').toDate();
    }

    if (earliestDate && date.isBefore(dayjs(earliestDate))) {
      return true;
    }
    if (latestDate && date.isAfter(dayjs(latestDate))) {
      return true;
    }

    return false;
  };

  const renderComponent = () => {
    switch (normalizedType) {
      case BaseCompType.Input:
        return (
          <Input
            value={internalValue}
            onChange={(e) => handleChange(e.target.value)}
            maxLength={limitedLength}
            allowClear
            style={{ width: '100%' }}
          />
        );
      case BaseCompType.InputNum:
        return (
          <InputNumber
            value={internalValue}
            onChange={handleChange}
            min={targetMin || undefined}
            max={targetMax || undefined}
            step={targetMultiples || undefined}
            stepStrictly={!!targetMultiples}
            precision={targetDecimalDigit}
            style={{ width: '100%' }}
            formatter={(value) => {
              if (dataFormat === DataFormatEnum.percentage) {
                return `${value}%`;
              }
              if (dataFormat === DataFormatEnum.money) {
                return `￥${value}`;
              }
              return value;
            }}
            parser={(value) => {
              if (dataFormat === DataFormatEnum.percentage) {
                return parseFloat(value.replace('%', ''));
              }
              if (dataFormat === DataFormatEnum.money) {
                return parseFloat(value.replace('￥', ''));
              }
              return parseFloat(value);
            }}
          />
        );
      case BaseCompType.DateTime:
        return (
          <DatePicker
            value={internalValue ? dayjs(internalValue, dateFormat) : null}
            onChange={(date) => handleChange(date ? date.format(dateFormat) : null)}
            format={dateFormat}
            disabledDate={disabledDate}
            style={{ width: '100%' }}
            allowClear
          />
        );
      case BaseCompType.DateRange:
        return (
          <RangePicker
            value={internalValue && internalValue.includes(',') 
              ? internalValue.split(',').map(d => dayjs(d.trim(), dateFormat)) 
              : null}
            onChange={(dates) => {
              if (dates) {
                handleChange(dates.map(date => date.format(dateFormat)).join(','));
              } else {
                handleChange(null);
              }
            }}
            format={dateFormat}
            disabledDate={disabledDate}
            style={{ width: '100%' }}
            allowClear
          />
        );
      case BaseCompType.SelectCtrl:
        return (
          <SelectCtrlWithoutForm
            value={internalValue}
            onChange={handleChange}
            field={{
              selectDatasource: selectDatasource,
              selectLevel: selectLevel,
            }}
            style={{ width: '100%' }}
          />
        );
      case BaseCompType.SelectDrop:
        return (
          <SelectDropWithoutForm
            value={internalValue}
            onChange={handleChange}
            field={{
              selectDatasource: selectDatasource,
              multiple: isMultiple,
              filterable: isFilter,
            }}
            format="string"
            style={{ width: '100%' }}
          />
        );
      default:
        return (
          <Input
            value={internalValue}
            onChange={(e) => handleChange(e.target.value)}
            style={{ width: '100%' }}
          />
        );
    }
  };

  return (
    <div className="smart-input" style={{ width: '100%' }}>
      {renderComponent()}
    </div>
  );
};

export default SmartInput;

// bone-business/tpa-sass-vue3/src/components/RenderEngine/base/SmartInput/index.vue
<script setup>
import { BaseCompType } from "@/enums";
import { createProps } from "./smartInput.js";
import SelectDropWithoutForm from "../SelectDropWithoutForm/index.vue";
import SelectCtrlWithoutForm from "../SelectCtrlWithoutForm/index.vue";
import { DataFormatEnum } from "@/enums/baseComp/DataFormatEnum";
import { SelectTypeEnum } from "@/enums/baseComp/SelectTypeEnum";
import { FilterTypeEnum } from "@/enums/baseComp/FilterTypeEnum";
import {
  getDateFormat,
  getDateRangeType,
  getDateTimeType,
} from "@/enums/baseComp/DateFormatEnum";
import { formatDate } from "@/utils/date";
import dayjs from "dayjs";

const modelValue = defineModel();
const props = defineProps(createProps());

const type = computed(() => {
  return props.type.replace("PK", "");
});

const isValidNumber = (value) =>
  value !== null && value !== undefined && !isNaN(Number(value));

const targetDecimalDigit = computed(() => {
  return isValidNumber(props.decimalDigit) && props.decimalDigit >= 0
    ? props.decimalDigit
    : 0;
});
const targetMin = computed(() => {
  return isValidNumber(props.min) ? Number(props.min) : null;
});
const targetMax = computed(() => {
  return isValidNumber(props.max) ? Number(props.max) : null;
});
const targetMultiples = computed(() => {
  return isValidNumber(props.multiples) && props.multiples > 0
    ? Number(props.multiples)
    : null;
});
const dateFormat = computed(() => {
  return getDateFormat(props.dateFormatType);
});
const dateTimeType = computed(() => {
  return getDateTimeType(props.dateFormatType);
});
const dateRangeType = computed(() => {
  return getDateRangeType(props.dateFormatType);
});
const selectDatasource = computed(() => {
  return props.selectDatasource;
});
const isMultiple = computed(() => {
  return props.selectType === SelectTypeEnum.multiple;
});
const isFilter = computed(() => {
  return props.filterType === FilterTypeEnum.Supported;
});

const disabledDate = (date) => {
  // 处理最早时间限制
  let earliestDate = null;
  if (props.earliestDatetimeType === 0 && props.earliestDatetime) {
    earliestDate = dayjs(props.earliestDatetime).toDate();
  } else if (props.earliestDatetimeType === 1) {
    earliestDate = dayjs().startOf("day").toDate();
  }

  // 处理最晚时间限制
  let latestDate = null;
  if (props.latestDatetimeType === 0 && props.latestDatetime) {
    latestDate = dayjs(props.latestDatetime).toDate();
  } else if (props.latestDatetimeType === 1) {
    latestDate = dayjs().endOf("day").toDate();
  }

  // 判断日期是否在范围之外
  if (earliestDate && date < earliestDate) {
    return true;
  }
  if (latestDate && date > latestDate) {
    return true;
  }

  return false;
};

const formatDateRange = (value) => {
  // 如果值是空值，直接返回空字符串
  if (value === null || value === undefined || value === "") {
    return "";
  }
  // 如果值是日期区间格式，处理日期
  if (typeof value === "string" && value.includes(",")) {
    const [startDate, endDate] = value.split(",").map((date) => date.trim());
    const formattedStartDate = formatDate(startDate, dateFormat.value);
    const formattedEndDate = formatDate(endDate, dateFormat.value);
    return [formattedStartDate, formattedEndDate];
  }

  // 如果值是单个日期，处理日期
  return formatDate(value, dateFormat.value);
};

const dateRangeValue = computed({
  get() {
    return formatDateRange(modelValue.value);
  },
  set(val) {
    modelValue.value = Array.isArray(val) ? val.join(",") : val;
  },
});
</script>

<template>
  <!-- 根据type自动选择组件 -->
  <div class="smart-input w-full">
    <template v-if="type === BaseCompType.Input">
      <el-input v-model="modelValue" :maxlength="limitedLength" clearable />
    </template>
    <template v-else-if="type === BaseCompType.InputNum">
      <el-input-number
        v-model="modelValue"
        style="width: 100%"
        :controls="false"
        :min="targetMin ?? undefined"
        :max="targetMax ?? undefined"
        :step="targetMultiples ?? undefined"
        :step-strictly="targetMultiples ? true : false"
        :precision="targetDecimalDigit ?? undefined"
        clearable
      >
        <template
          #suffix
          v-if="
            dataFormat === DataFormatEnum.percentage ||
            dataFormat === DataFormatEnum.money
          "
        >
          <span>
            {{ dataFormat === DataFormatEnum.percentage ? "%" : "￥" }}
          </span>
        </template>
      </el-input-number>
    </template>
    <template v-else-if="type === BaseCompType.DateTime">
      <el-date-picker
        v-model="modelValue"
        :type="dateTimeType"
        :format="dateFormat"
        :value-format="dateFormat"
        :disabled-date="disabledDate"
        style="width: 100%"
        clearable
      />
    </template>
    <template v-else-if="type === BaseCompType.DateRange">
      <el-date-picker
        v-model="dateRangeValue"
        :type="dateRangeType"
        :format="dateFormat"
        :value-format="dateFormat"
        range-separator="至"
        :disabled-date="disabledDate"
        unlink-panels
        style="width: 100%"
        clearable
      />
    </template>
    <template v-else-if="type === BaseCompType.SelectCtrl">
      <SelectCtrlWithoutForm
        v-model="modelValue"
        :field="{
          selectDatasource: selectDatasource,
          selectLevel: selectLevel,
        }"
        style="width: 100%"
      />
    </template>
    <template v-else-if="type === BaseCompType.SelectDrop">
      <SelectDropWithoutForm
        v-model="modelValue"
        :field="{
          selectDatasource: selectDatasource,
          multiple: isMultiple,
          filterable: isFilter,
        }"
        format="string"
        style="width: 100%"
      />
    </template>
  </div>
</template>

<style lang="scss" scoped>
:deep(.el-input-number.is-without-controls .el-input__wrapper) {
  padding: 1px 11px !important;
}

:deep(.el-input-number .el-input__inner) {
  text-align: left;
}
</style>
